aliases:
  - &hacking
    name: Hack Qt5Core
    command: 'set -x; strip --remove-section=.note.ABI-tag /usr/lib/libQt5Core.so.5'
  - &configure
    name: Fetching submodules
    command: 'bash configure.sh'
  - &building
    name: Building
    command: 'cmake --build build -j2'
  - &testing
    name: Unit Testing
    command: 'pushd build && ctest --output-on-failure -j2'
    
version: 2
jobs:
  build-gcc-default:
    docker:
      - image: enree/arch-gammaray:latest
    steps:
      - checkout
      - run: *hacking
      - run: *configure
      - run:
          name: Generating build files
          command: 'cmake -Bbuild -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DQT_QMAKE_EXECUTABLE=qmake -DGAMMARAY_INSTALL_PATH=/opt/gammaray'
      - run: *building
      - run: *testing
  build-clang-debug:
    docker:
      - image: enree/arch-gammaray:latest
    steps:
      - checkout
      - run: *hacking
      - run: *configure
      - run:
          name: Generating build files
          command: 'cmake -Bbuild -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug -DQT_QMAKE_EXECUTABLE=qmake -DSANITIZE=ON -DGAMMARAY_INSTALL_PATH=/opt/gammaray'
      - run: *building
      - run: *testing
  build-clang-release:
    docker:
      - image: enree/arch-gammaray:latest
    steps:
      - checkout
      - run: *hacking
      - run: *configure
      - run:
          name: Generating build files
          command: 'cmake -Bbuild -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release -DQT_QMAKE_EXECUTABLE=qmake -DGAMMARAY_INSTALL_PATH=/opt/gammaray'
      - run: *building
      - run: *testing
workflows:
  version: 2
  build:
    jobs:
      - build-gcc-default
      - build-clang-release
      - build-clang-debug
